# Cria uma nova turma
POST http://localhost:3003/class
Content-Type: application/json

{
    "id":6,
    "nome":"Barros",
    "data_inicio": "2023-03-01",
    "data_fim":"2024-03-01",
    "modulo":1,    
    "tipo":"integral"
}

### Cria um novo estudante
POST http://localhost:3003/student
Content-Type: application/json

{
    "id":3,
    "nome":"Eduardo",
    "email": "eduardo@exemplo.com",
    "data_nasc":"1990-02-03",
    "hobbies":["Caminhar", "jogar bola"], 
    "turma_id":3 
}

### Cria um novo professor
POST http://localhost:3003/teacher
Content-Type: application/json

{
    "id":4,
    "nome":"Rafinha",
    "email": "rafinha@exemplo.com",
    "data_nasc":"1975-02-03",
    "especialidades":["REACT", "CSS", "TYPESCRIPT"], 
    "turma_id":3  
}

### Troca professor de turma 
PUT http://localhost:3003/teacher/update
Content-Type: application/json

{
    "docente_id":1,
    "turma_id":9
}

### Troca aluno de turma
PUT http://localhost:3003/student/update
Content-Type: application/json

{
    "estudante_id": 1,
    "turma_id": 3
}