POST http://localhost:3003/class
Content-Type: application/json

{
    "id":1,
    "nome":"Jemison",
    "data_inicio": "2022-04-20",
    "data_fim":"2023-04-20",
    "modulo":7,    
    "tipo":"noturno"
}
