# Cria uma nova turma
POST https://labenu-system-backend-ofz0f7s54-rafix923.vercel.app/class
Content-Type: application/json

{
    "id":7,
    "nome":"Tesla",
    "data_inicio": "2024-04-01",
    "data_fim":"2025-04-01",
    "modulo":0,    
    "tipo":"integral"
}

### Seleciona turmas ativas
GET  https://labenu-system-backend-ofz0f7s54-rafix923.vercel.app/class/active

### Cria um novo estudante
POST  https://labenu-system-backend-ofz0f7s54-rafix923.vercel.app/student
Content-Type: application/json

{
    "id":8,
    "nome":"David",
    "email": "davidr@exemplo.com",
    "data_nasc":"1980-09-02",
    "hobbies":["Jogar bola", "Assistir filmes"], 
    "turma_id":5 
}

### Busca estudante através do nome
GET https://labenu-system-backend-ofz0f7s54-rafix923.vercel.app/student?nome=David

### Cria um novo professor
POST http://localhost:3003/teacher
Content-Type: application/json

{
    "id":2,
    "nome":"Madalena",
    "email": "madalena@exemplo.com",
    "data_nasc":"1975-02-03",
    "especialidades":["REACT", "CSS", "TYPESCRIPT"], 
    "turma_id":3  
}

### Lista todos os professores
GET https://labenu-system-backend-ofz0f7s54-rafix923.vercel.app/teacher/all

### Troca professor de turma 
PUT https://labenu-system-backend-ofz0f7s54-rafix923.vercel.app/teacher/update
Content-Type: application/json

{
    "docente_id":1,
    "turma_id":3
}

### Troca aluno de turma
PUT https://labenu-system-backend-ofz0f7s54-rafix923.vercel.app/student/update
Content-Type: application/json

{
    "estudante_id": 8,
    "turma_id": 1
}